#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "Call script as ... <parquet|hdf5> "
    exit
fi

[[ $1 == "parquet" ]] && ext="parquet" || ext="h5"

start=$(date +%s)

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2014.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2014 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2015.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2015 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2016.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2016 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2017.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2017 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2018.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2018 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2019.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2019 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2020.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2020 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2021.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2021 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2022.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2022 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2023.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2023 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_location_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs/$1/tickets_w_ms_hs_2024.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/landmarks/landmarks_NYC_individual_processed.csv --df2_name_parameter "LPC_NAME" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li/$1 --output_name_column "Closest Individual Landmark" --output_distance_column "Distance to CIL" --output_name tickets_w_ms_hs_li_2024 --data_format $1

end=$(date +%s)
echo "Individual Landmarks augmentations for $1-Dask took $(expr $end - $start) seconds."
