#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "Call script as ... <parquet|hdf5> "
    exit
fi

[[ $1 == "parquet" ]] && ext="parquet" || ext="h5"

start=$(date +%s)

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2014.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2014 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2015.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2015 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2016.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2016 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2017.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2017 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2018.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2018 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2019.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2019 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2020.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2020 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2021.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2021 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2022.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2022 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2023.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2023 --data_format $1

python /d/hpc/home/rj7149/BD/project/big-data-project/data_scripts/data_augmentations/merge_business_data.py --tickets_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls/$1/tickets_w_ms_hs_li_ls_2024.$ext --df2_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/additional_data/businesses/businesses_NYC_2023_processed.csv --df2_name_parameter "Business Name" --output_location /d/hpc/projects/FRI/bigdata/students/lsrj/data/aggregated_data/w+ms+hs+li+ls+b/$1 --output_name_column "Closest Business" --output_distance_column "Distance to CB" --output_name tickets_w_ms_hs_li_ls_b_2024 --data_format $1

end=$(date +%s)
echo "Businesses augmentations for $1-Dask took $(expr $end - $start) seconds."
