DataSchema = {
    "Summons Number": "float64",
    "Plate ID": "str",
    "Registration State": "str",
    "Plate Type": "str",
    "Issue Date": "str",
    "Violation Code": "float64",
    "Vehicle Body Type": "str",
    "Vehicle Make": "str",
    "Issuing Agency": "str",
    "Street Code1": "float64",
    "Street Code2": "float64",
    "Street Code3": "float64",
    "Vehicle Expiration Date": "float64",
    "Violation Location": "str",
    "Violation Precinct": "float64",
    "Issuer Precinct": "float64",
    "Issuer Code": "float64",
    "Issuer Command": "str",
    "Issuer Squad": "str",
    "Violation Time": "str",
    "Time First Observed": "str",
    "Violation County": "str",
    "Violation In Front Of Or Opposite": "str",
    "Number": "str",
    "Street": "str",
    "Intersecting Street": "str",
    "Date First Observed": "float64",
    "Law Section": "float64",
    "Sub Division": "str",
    "Violation Legal Code": "str",
    "Days Parking In Effect    ": "str",
    "From Hours In Effect": "str",
    "To Hours In Effect": "str",
    "Vehicle Color": "str",
    "Unregistered Vehicle?": "str",
    "Vehicle Year": "float64",
    "Meter Number": "str",
    "Feet From Curb": "float64",
    "Violation Post Code": "str",
    "Violation Description": "str",
    "No Standing or Stopping Violation": "str",
    "Hydrant Violation": "str",
    "Double Parking Violation": "str",
}