DataSchema = {
    "SummonsNumber": "float64",
    "PlateID": "str",
    "RegistrationState": "str",
    "PlateType": "str",
    "IssueDate": "str",
    "ViolationCode": "float64",
    "VehicleBodyType": "str",
    "VehicleMake": "str",
    "IssuingAgency": "str",
    "StreetCode1": "float64",
    "StreetCode2": "float64",
    "StreetCode3": "float64",
    "VehicleExpirationDate": "float64",
    "Violation Location": "str",
    "ViolationPrecinct": "float64",
    "IssuePrecinct": "float64",
    "IssuerCode": "float64",
    "IssuerCommand": "str",
    "Issuer Squad": "str",
    "ViolationTime": "str",
    "Time First Observed": "str",
    "ViolationCounty": "str",
    "ViolationInFrontOfOrOpposite": "str",
    "House Number": "str",
    "StreetName": "str",
    "IntersectingStreet": "str",
    "DateFirstObserved": "float64",
    "LawSection": "float64",
    "SubDivision": "str",
    "Violation Legal Code": "str",
    "DaysParkingInEffect": "str",
    "FromHoursInEffect": "str",
    "ToHoursInEffect": "str",
    "VehicleColor": "str",
    "Unregistered Vehicle?": "str",
    "VehicleYear": "float64",
    "MeterNumber": "str",
    "FeetFromVurb": "float64",
    "Violation Post Code": "str",
    "Violation Description": "str",
    "NoStandingOrStoppingViolation": "str",
    "HydrantViolation": "str",
    "DoubleParkingViolation": "str",
}